FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
WORKDIR /src
COPY backend/Week4Week5.Api/Week4Week5.Api.csproj backend/Week4Week5.Api/
COPY backend/Week4Week5.Worker/Week4Week5.Worker.csproj backend/Week4Week5.Worker/
RUN dotnet restore backend/Week4Week5.Worker/Week4Week5.Worker.csproj
COPY backend/Week4Week5.Api/ backend/Week4Week5.Api/
COPY backend/Week4Week5.Worker/ backend/Week4Week5.Worker/
RUN dotnet publish backend/Week4Week5.Worker/Week4Week5.Worker.csproj -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/runtime:8.0-alpine AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Week4Week5.Worker.dll"]